### ISSUE TITLE
Allow users to disable monitoring at run time

### ISSUE THREAD

**Issue by cw75** [cw75/tiered-storage#51]

**Comment by vsreekanti** [comment]
I think this is actually a moot point, @cw75. The server and routing tier never send messages to the monitoring system other than an asynchronous, "Hey, I'm alive!" kinda thing. Everything else is the monitoring system notifying the other services about changes. If those messages never come, nothing will ever change.

The only other thing that I can think of is storing metadata, but if we're running without monitoring, it's clearly a small / test deployment, so this shouldn't be an issue either. I think we can close this unless there's something I'm missing.
