### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by vsreekanti** [cw75/tiered-storage#61]
#60 made me realize that we have inconsistent styles, for example, around `#define` guards. By default, I usually go with [Google](https://google.github.io/styleguide/cppguide.html)'s style guides, but I don't know a ton about "good" C++ development, so I'm happy to defer to anyone else with stronger opinions on the subject. Either way, we are inconsistent right now, so we should fix that. 

Once we finish this refactor, we should also probably run `clang-format` on the code because I'm pretty sure we have some weird indentation stuff going on, imports are not alphabetical, etc. I'll eventually put this into the Travis build as well. 

@cw75 @jhellerstein: Tagging you guys, so that we can come to a decision on this soon and move forward.

**Comment by jhellerstein** [comment]
I am totally agnostic to style, but I agree we should (a) pick a style, and (b) get linter definitions for that style into our editors and build process. There's nice clang integration into sublime for example.

**Comment by vsreekanti** [comment]
Note: Part of this cleanup is reformatting the names all of the global `consts` defined in `common.hpp`.
