### ISSUE TITLE
fix the race condition during actor joining/departure with lattices

### ISSUE THREAD

**Issue by cw75** [cw75/tiered-storage#8]

**Comment by vsreekanti** [comment]
@cw75, this is fixed now, right?

**Comment by cw75** [comment]
This is not fixed by using lattices, but I think based on our current design, this problem does not exist any more because local ebs thread joining/departure won't be reflected in the global ebs hash ring.

**Comment by vsreekanti** [comment]
Right. Actually not clear to me what lattices had to do with this, but closing this since it's no longer an issue. 😃
